defaults: &defaults
  docker:
    - image: circleci/node:jessie-browsers

version: 2.1
jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Dependency install
          command: NODE_ENV=development npm ci
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Build from source
          command: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules
            - lib
